apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: recommendationservice
  namespace: sre-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recommendationservice
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80
