steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/gcp-getting-started-lab-jp/sre-app:$SHORT_SHA",
        ".",
      ]
    dir: "./"
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/gcp-getting-started-lab-jp/sre-app:$SHORT_SHA",
      ]
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "set"
      - "image"
      - "deployment/sre-app-deployment"
      - "sre-app=asia-northeast1-docker.pkg.dev/$PROJECT_ID/gcp-getting-started-lab-jp/sre-app:$SHORT_SHA"
      - "-n"
      - "sre-ns"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-b"
      - "CLOUDSDK_CONTAINER_CLUSTER=sre-cluster"
